service: football-match-api

provider:
  name: aws
  runtime: java17
  region: us-east-2

functions:
  createMatch:
    handler: com.alejandrocastaneda.serverles_guru_challenge.infrastructure.adapter.inbound.lambda.LambdaHandler::handleRequest
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: createMatch
    events:
      - http:
          path: football-match
          method: post

  getMatch:
    handler: com.alejandrocastaneda.serverles_guru_challenge.infrastructure.adapter.inbound.lambda.LambdaHandler::handleRequest
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getMatch
    events:
      - http:
          path: football-match/{localTeam}/{awayTeam}/{matchDate}
          method: get

  updateScore:
    handler: com.alejandrocastaneda.serverles_guru_challenge.infrastructure.adapter.inbound.lambda.LambdaHandler::handleRequest
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: updateScore
    events:
      - http:
          path: football-match
          method: put

  deleteMatch:
    handler: com.alejandrocastaneda.serverles_guru_challenge.infrastructure.adapter.inbound.lambda.LambdaHandler::handleRequest
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: deleteMatch
    events:
      - http:
          path: football-match
          method: delete

package:
  artifact: ../../../build/libs/serverles-guru-challenge-0.0.1-SNAPSHOT.jar