plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.3'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'jacoco'
}

group = 'com.alejandrocastaneda'
version = '0.0.1-SNAPSHOT'
description = 'This is a CRUD application for servers guru technical challenge'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

jacoco {
	toolVersion = "0.8.12"
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-rest'
	implementation 'org.springframework.boot:spring-boot-starter-webflux'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	testImplementation 'org.springframework.boot:spring-boot-starter-data-rest-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webflux-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	//AWS dependencies
	implementation platform("software.amazon.awssdk:bom:2.25.10")

	implementation "software.amazon.awssdk:dynamodb"
	implementation "software.amazon.awssdk:dynamodb-enhanced"

	implementation 'org.springframework.cloud:spring-cloud-function-adapter-aws'
	implementation 'com.amazonaws:aws-lambda-java-core:1.2.3'
	
}

test {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
	dependsOn test

	classDirectories.setFrom(
			files(classDirectories.files.collect {
				fileTree(dir: it, exclude: [
						'**/ServerlesGuruChallengeApplication.class',
						'**/exceptionhandler/**',
						'**/config/**'
				])
			})
	)

	reports {
		xml.required = true
		html.required = true
	}
}

jacocoTestCoverageVerification {
	violationRules {
		rule {
			element = 'BUNDLE'

			excludes = [
					'**/ServerlesGuruChallengeApplication',
					'**/exceptionhandler/**',
					'**/config/**'
			]

			limit {
				counter = 'LINE'
				value = 'COVEREDRATIO'
				minimum = 0.80
			}
		}
	}
}

tasks.named('test') {
	useJUnitPlatform()
}
check.dependsOn jacocoTestCoverageVerification

dependencyManagement {
	imports {
		mavenBom "org.springframework.cloud:spring-cloud-dependencies:2023.0.3"
	}
}
