service: football-match-api

provider:
  name: aws
  runtime: java17
  region: us-east-2

functions:
  createMatch:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: createMatch
      SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.alejandrocastaneda.serverles_guru_challenge
    events:
      - http:
          path: api/football-match
          method: post

  getMatch:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getMatch
      SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.alejandrocastaneda.serverles_guru_challenge
    events:
      - http:
          path: api/football-match/{localTeam}/{awayTeam}/{matchDate}
          method: get

  updateScore:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: updateScore
      SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.alejandrocastaneda.serverles_guru_challenge
    events:
      - http:
          path: api/football-match
          method: put

  deleteMatch:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: deleteMatch
      SPRING_CLOUD_FUNCTION_SCAN_PACKAGES: com.alejandrocastaneda.serverles_guru_challenge
    events:
      - http:
          path: api/football-match
          method: delete

package:
  artifact: build/libs/app.jar