service: football-match-api

provider:
  name: aws
  runtime: java17
  region: us-east-2

functions:
  createMatch:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: createMatch
    events:
      - http:
          path: api/football-match
          method: post

  getMatch:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: getMatch
    events:
      - http:
          path: api/football-match/{localTeam}/{awayTeam}/{matchDate}
          method: get

  updateScore:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: updateScore
    events:
      - http:
          path: api/football-match
          method: put

  deleteMatch:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker
    environment:
      SPRING_CLOUD_FUNCTION_DEFINITION: deleteMatch
    events:
      - http:
          path: api/football-match
          method: delete

package:
  artifact: build/libs/serverles-guru-challenge-0.0.1-SNAPSHOT.jar